### ISSUE TITLE
distutils classifies as THIRD_PARTY instead of BUILTIN

### ISSUE THREAD

**Issue by bluelight773** [asottile/aspy.refactor_imports#127]
I'm using python3.8.

```
from aspy.refactor_imports.classify import classify_import
print(classify_import("distutils"))
```

Expected:
`BUILTIN`

Actual:
`THIRD_PARTY`

Upon a closer look, I see that  you specifically force `distutils` to be classified as `THIRD_PARTY` though I don't understand the reasoning given it still seems to be part of the standard library or at least seems to be [documented](https://docs.python.org/3/library/distutils.html) as such. Also, I don't see functionality such as `distutils.dir_util.copy_tree` having moved into `setuptools`.
```py
    # force distutils to be "third party" after being gobbled by setuptools
    elif base == 'distutils':
        return ImportType.THIRD_PARTY
```

**Comment by asottile** [comment]
install a recent setuptools and look at `distutils.__file__`

as you can tell from the code you linked this is very intentional
