### ISSUE TITLE
Relative import sorted incorrect.

### ISSUE THREAD

**Issue by coldnight** [asottile/aspy.refactor_imports#17]
I am using [this](https://github.com/coldnight/reorder_python_imports), and I noticed the relative import sorted incorrect. Here is the code

```python
import pprint
from aspy.refactor_imports.import_obj import FromImport

objs = sorted([
    FromImport.from_str('from a import foo'),
    FromImport.from_str('from a.b import baz'),
    FromImport.from_str('from a import bar'),
    FromImport.from_str('from a import bar as buz'),
    FromImport.from_str('from a import bar as baz'),
    FromImport.from_str('from .a import bar as baz'),
    FromImport.from_str('from . import bar as baz'),
    FromImport.from_str('from .aa.bb import bar as baz'),
])
pprint.pprint([i.to_text() for i in objs])
```

Excepted: 

```text
[u'from a import bar\n',
 u'from a import bar as baz\n',
 u'from a import bar as buz\n',
 u'from a import foo\n',
 u'from a.b import baz\n',
 u'from .aa.bb import bar as baz\n',
 u'from .a import bar as baz\n',
 u'from . import bar as baz\n',
]
```

Got: 

```text
[u'from . import bar as baz\n',
 u'from .a import bar as baz\n',
 u'from .aa.bb import bar as baz\n',
 u'from a import bar\n',
 u'from a import bar as baz\n',
 u'from a import bar as buz\n',
 u'from a import foo\n',
 u'from a.b import baz\n']
```

**Comment by asottile** [comment]
The sorting that you get is what I expect? `'.' < 'a'` -- could you elaborate on why you expect the other sorting?

**Comment by coldnight** [comment]
Because I think the import from internal should after the third party import, and relative import always from internal. Assume I have a package named `pkg`, I import some module from third party and internal, I think the below style would be better.

```python

import pre_commit
from pre_commit import util

from pkg import demo

from .demo import xxx
```

**Comment by asottile** [comment]
This example demonstrates the intent that `reorder-python-imports` has:

```python
from __future__ import absolute_import

import sys
from sys import version_info

import pre_commit
from pre_commit import main

import mymod
from . import bar
from .submod import baz
from mymod import foo
```

[From this documentation](https://github.com/asottile/reorder_python_imports#separates-imports-into-three-sections)

Internal imports *are* always after third party modules (including explicit relative imports).  Explicit relative imports are sorted lexicographically with other internal imports

**Comment by coldnight** [comment]
Ok I see, thanks for your reply. I'd like put the relative import as a new partition split from the non relative internal imports and use a line to split them.

**Comment by asottile** [comment]
I'd take a PR which adds that as an option if you'd like -- I think all you'd need to do is add a `is_explicit_relative` property to the import item and add an option in `reorder_python_imports`

**Comment by coldnight** [comment]
Sounds good, I will try that later.
